language: python

python:
  - "3.6"

# env variables
env:
  - DJANGO_SETTINGS_MODULE="authors.settings"

# install project dependencies
install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c "create database authors_haven_test;" -U postgres
  - psql -c "CREATE USER tester WITH PASSWORD 'tester';" -U postgres
  - psql -c "ALTER USER tester CREATEDB;" -U postgres

# make migrations and run tests
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test

# produce coverage report
after_success:
  - coveralls
