# Generated by Django 2.1.4 on 2019-01-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_taglist'),
        ('articles', '0003_reaction'),
    ]

    operations = [
    ]
